# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hamed R. Nik
description: > # this means to ignore newlines until "baseurl:"
   My name is Hamed. I was born and grew up in Iran, but have
   been living in Dublin, Ireland since 2013. I am a Free Software enthusiast.
   Currently I'm working at AYLIEN
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hamedrnik.com" # the base hostname & protocol for your site
keywords: Hamed Ramezanian Nik,Personal Website,Hamed R. Nik,Hamed
# Build settings
markdown: kramdown
