# Site settings
title: Hamed R. Nik
description: >
   My name is Hamed. I was born and grew up in Iran, but have been living in Dublin, Ireland since 2013. I am a Free Software enthusiast. Currently, I’m working at AYLIEN.
baseurl: ""
url: "http://hamedrnik.com"
keywords: Hamed Ramezanian Nik,Personal Website,Hamed R. Nik,Hamed
markdown: kramdown
